package GUI;


import commonInterface.IUser;
import entities.User;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alessio_Gregory_Ricky
 */
public class MainUserGUI extends javax.swing.JFrame implements UserGUI{

    /**
     * Creates new form MainUserGUI
     */
    public MainUserGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBCallCenter = new javax.swing.JComboBox();
        CBOffice1 = new javax.swing.JComboBox();
        CBOffice2 = new javax.swing.JComboBox();
        CBOffice3 = new javax.swing.JComboBox();
        CBOffice4 = new javax.swing.JComboBox();
        LCallCenter = new javax.swing.JLabel();
        LOffice1 = new javax.swing.JLabel();
        LOffice2 = new javax.swing.JLabel();
        LOffice3 = new javax.swing.JLabel();
        LOffice4 = new javax.swing.JLabel();
        LResponce = new javax.swing.JLabel();
        ButtonConferma = new javax.swing.JButton();
        LName = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User GUI");
        setResizable(false);

        CBCallCenter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "30", "40", "50" }));

        CBOffice1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "11", "12", "13", "14", "21", "22", "23", "24", "31", "32", "33", "34", "41", "42", "43", "44", "51", "52", "53", "54" }));
        CBOffice1.setSelectedIndex(1);
        CBOffice1.setToolTipText("");

        CBOffice2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "11", "12", "13", "14", "21", "22", "23", "24", "31", "32", "33", "34", "41", "42", "43", "44", "51", "52", "53", "54" }));
        CBOffice2.setSelectedIndex(5);
        CBOffice2.setToolTipText("");

        CBOffice3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "11", "12", "13", "14", "21", "22", "23", "24", "31", "32", "33", "34", "41", "42", "43", "44", "51", "52", "53", "54" }));
        CBOffice3.setSelectedIndex(9);
        CBOffice3.setToolTipText("");

        CBOffice4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "11", "12", "13", "14", "21", "22", "23", "24", "31", "32", "33", "34", "41", "42", "43", "44", "51", "52", "53", "54" }));
        CBOffice4.setSelectedIndex(13);
        CBOffice4.setToolTipText("");

        LCallCenter.setText("CallCenter");

        LOffice1.setText("Office1");

        LOffice2.setText("Office2");

        LOffice3.setText("Office3");

        LOffice4.setText("Office4");

        LResponce.setText("Responce");

        ButtonConferma.setText("Conferma");
        ButtonConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfermaActionPerformed(evt);
            }
        });

        LName.setText("Nome");

        TxtName.setText("Digita il nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBCallCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LCallCenter)
                            .addComponent(LName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBOffice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LOffice1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBOffice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LOffice2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBOffice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LOffice3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LOffice4)
                                    .addComponent(CBOffice4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LResponce, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonConferma)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCallCenter)
                    .addComponent(LOffice1)
                    .addComponent(LOffice2)
                    .addComponent(LOffice3)
                    .addComponent(LOffice4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBCallCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBOffice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBOffice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBOffice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBOffice4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LName)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(ButtonConferma)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LResponce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfermaActionPerformed

        //Callcenter id
        Long Callcenter=Long.parseLong(((String)CBCallCenter.getSelectedItem()).trim());
        //Offices id
        Long office1=Long.parseLong(((String)CBOffice1.getSelectedItem()).trim());
        Long office2=Long.parseLong(((String)CBOffice2.getSelectedItem()).trim());
        Long office3=Long.parseLong(((String)CBOffice3.getSelectedItem()).trim());
        Long office4=Long.parseLong(((String)CBOffice4.getSelectedItem()).trim());
        
        //Controllo che non ci sono due uffici uguali
        if(office2==office1){
            JOptionPane.showMessageDialog(this, "Ci sono due uffici con lo stesso nome", "Errore", WIDTH);
        }
        else if(office3==office2||office3==office1){
            JOptionPane.showMessageDialog(this, "Ci sono due uffici con lo stesso nome", "Errore", WIDTH);
        }
        else if(office4==office3||office4==office2||office4==office1){
            JOptionPane.showMessageDialog(this, "Ci sono due uffici con lo stesso nome", "Errore", WIDTH);
        }
        else{
            ButtonConferma.setEnabled(false);
            //Creo Ogetto user
            User user=new User(TxtName.getText());
            if(office1>10) user.addOffice(office1);
            if(office2>10) user.addOffice(office2);
            if(office3>10) user.addOffice(office3);
            if(office4>10) user.addOffice(office4);
            if(Callcenter>9)user.setCallCenterID(Callcenter);
            JOptionPane.showMessageDialog(this, "Mando la richiesta al callcenter: "+Callcenter+"\n"
                                                +"Office: "+office1+"\n"
                                                +"Office: "+office2+"\n"
                                                +"Office: "+office3+"\n"
                                                +"Office: "+office4+"\n"
                                                ,"Conferma",WIDTH);
            user.setGUI(this);
            user.init();
            //Il bottone viene riabilitato quando si riceve la risposta
            
        }
    }//GEN-LAST:event_ButtonConfermaActionPerformed

    @Override
    public void setResponce(final String txt){
        LResponce.setText("Responce: "+txt);
        try {
            Thread.sleep(5000);
        } catch (InterruptedException ex) {
            ex.printStackTrace(System.out);
        }
        ButtonConferma.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new MainUserGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConferma;
    private javax.swing.JComboBox CBCallCenter;
    private javax.swing.JComboBox CBOffice1;
    private javax.swing.JComboBox CBOffice2;
    private javax.swing.JComboBox CBOffice3;
    private javax.swing.JComboBox CBOffice4;
    private javax.swing.JLabel LCallCenter;
    private javax.swing.JLabel LName;
    private javax.swing.JLabel LOffice1;
    private javax.swing.JLabel LOffice2;
    private javax.swing.JLabel LOffice3;
    private javax.swing.JLabel LOffice4;
    private javax.swing.JLabel LResponce;
    private javax.swing.JTextField TxtName;
    // End of variables declaration//GEN-END:variables
}
